language: java
jdk: oraclejdk8
addons:
  mariadb: '10.0'
before_install:
- mysql -e 'CREATE DATABASE menti;'
notifications:
  slack:
    secure: XRNA+/Us5QkK16UtP33aKcaDAVVOE0JcDakHLjJkSDQPTm30xL+ZRduruICBH1ul32mED6Fn7H0CaWAedYGCIXcPid/6STasNdBjKKSO0IezxnbiDju5Yhjy+BlbgHUFY9Xjd/oDHVfxOy8IayT7tAd5/zalztsFSaWJ9tH+uRlpjusWB84+QQ+8vc9JXmv/sMBUqJTWxOrN6NDO1eU50gL2A2ces61esxWnYZsCdRJ3JGXDzkPP4GaXgKPxmmwPiYBv7s5wkipnkTCW9LYyL1pqF+y3tIJKF4FEmSrFc9xFo0gKXx7Gl65rtTzaiOikgW1eFMczd71jxjL83vS/1BIU+FmElOKxbBUPR348ilXPdsYbP6ofwuOJna9+FKF6/T463/aBBlFz6/pXO1XAN5PzcA5LwOkSsk3+/N494dKxVxS6e7f0UY8f1gB5h8BBg4g9Gi/iGC6qQUI+tGClk3Ynrf4NmSea/Kk2MQub4gblflclZ9vk0lY2jnw90cF4qKBgqrOKmnmMb6gB6JmdeOCz/MkhkAanSlbDlF+l6Fmk2tijJFdj0aSm+YrhleZZ9InG7mJXJU8BKRtQcuHRcOt19WzO/mSsrr+2exOx5c4DtV5LpuTODzqjxFoqL76zXFYXBbIXkXBR1Iq+T0XExRkUYVhfube7AcppgaZviT8=
    on_success: always
    on_failure: always
