language: java
jdk: oraclejdk8
addons:
  mariadb: '10.0'
before_install:
- mysql -e 'CREATE DATABASE menti;'
notifications:
  slack:
    secure: ajYeNgtyzBfrh7ai5eHvUuChH0SzBHkQDmgDS/vWtgWjiRxu5QtIJ5nS3DkLaDBTExsZ/wjXv74nPdeyC7EJgQvp8ZoHleCRmEsY1/lLONy7R1v4AIPSxZOEsQO/0rQYv82AynMXHFx/3B67XFSHn5KIGSIj3ql2pxqR2bf9W1PAVxcuxllmF4z4q7WQ26uil5lET4QSVCddMTpYPXAqPimj8CEMZGVpMhi4teMV13VmCxvlJWZfqtaZ2XxdOhMJ91xYAi4n4DSRMksdXQTyw5/XJ1es9RLm6awBReolexK2tgITRFdCse9PLjJZC6sK4Tnw/xO86AwWsHd1tiSvHVKGgT1TxwIE/PpOQMif64jlcytN0fmcSCheOKv1KbAqmFcnSCXyKnpFHjkkrZbw9wkW2HJwyT3q4Mm4dSV5ZEa3BKyZgtX5WX2FrTWtg6SA1opFULgi800ULUyMyo6VBLosE4x1hqR4n+uTLMHUYRLGwSpHqc33OcAQ/Z3EG94Ac5mQBpw//kbkWrNZi9zlAkhmcwQ7AQlQsJTCMzHrciPcv7Zhl4RFYvEXyc7rwC1jO6QaQsXMy1cKWcCp2KEOZNNP0KAes21q14/wekdp9Hegh1VGyCYB8H6ImvtZ83HVCD15YKVotHfDMTyvxgVvBprZdDGcON6E0RZlvreg65g=
deploy:
  provider: heroku
  api_key:
    secure: XKHPG7HR5pn2sLVjT7YM4Il58X8qzR4aG+qk+Y/ZO5CEtqIooxqZTeIJjIUSnbIBmL88UC+N7VuK089weqDl+DPCFNJvl7FrijDzApTA9q9QnwfDyLMjc8ioAnn0p7/x8r1VM94KomHynPmr3QeMui+bB44Pa1p6LRGUAiyR3z3VFUoGygtytXufCkSzCQJJ+RmVlUsj46NmT6T21beQfwj3pgJJWnouf6M9/9nisQKRK2DWSHLon68h+TilOkRabgt3hn7Kc7T+XADp/UWv3Y+HNweCmADgEmvWWqMtdalHR7o3957hRrrA1HHdNXT6z2mR2rWfoe8vQwgtoMhsyiZPEmqLIV0NGqCHWipw+pcf0AT2MtVsP7lXrq8H9tsLPQ4G+K0DuSLZ53AcDYF7PRbguYBFTwyIaxojCyXykakBCMrFnLG9f9797qarRtqcqav/1SEmlaAGBX372dLxk8R0SzEtIx1Us1cmBcbQLu4oc8sQHFQ3Rrc1FgY91okJuLrSDVL922ofgyJmMowtaQ6UnNl53vEeKBtWeCiw/4tL6PJmhX5q8iZNM6nGsgLpjjhF0hIpYc4fMagaAVuqAF0TuvMNThIvvCinlbO2PfWtWCWHCnWtBUFvofY610l9SM4aIredeQ7yLjGkQ/rpwqfeKSKoNofOZ7LhgW6W1zc=
  app: menti