language: java
jdk: oraclejdk8
addons:
  mariadb: '10.0'
before_install:
- mysql -e 'CREATE DATABASE menti;'
notifications:
  slack:
    secure: ajYeNgtyzBfrh7ai5eHvUuChH0SzBHkQDmgDS/vWtgWjiRxu5QtIJ5nS3DkLaDBTExsZ/wjXv74nPdeyC7EJgQvp8ZoHleCRmEsY1/lLONy7R1v4AIPSxZOEsQO/0rQYv82AynMXHFx/3B67XFSHn5KIGSIj3ql2pxqR2bf9W1PAVxcuxllmF4z4q7WQ26uil5lET4QSVCddMTpYPXAqPimj8CEMZGVpMhi4teMV13VmCxvlJWZfqtaZ2XxdOhMJ91xYAi4n4DSRMksdXQTyw5/XJ1es9RLm6awBReolexK2tgITRFdCse9PLjJZC6sK4Tnw/xO86AwWsHd1tiSvHVKGgT1TxwIE/PpOQMif64jlcytN0fmcSCheOKv1KbAqmFcnSCXyKnpFHjkkrZbw9wkW2HJwyT3q4Mm4dSV5ZEa3BKyZgtX5WX2FrTWtg6SA1opFULgi800ULUyMyo6VBLosE4x1hqR4n+uTLMHUYRLGwSpHqc33OcAQ/Z3EG94Ac5mQBpw//kbkWrNZi9zlAkhmcwQ7AQlQsJTCMzHrciPcv7Zhl4RFYvEXyc7rwC1jO6QaQsXMy1cKWcCp2KEOZNNP0KAes21q14/wekdp9Hegh1VGyCYB8H6ImvtZ83HVCD15YKVotHfDMTyvxgVvBprZdDGcON6E0RZlvreg65g=
deploy:
  provider: heroku
  api_key:
    secure: TNUVXDWorzTnFzh0km9xfi9uXyYll/SwNliGW/20P1cjAD1nCnB49LRlPT8Iu1/h+9eZdVXCs5/imca0S8QHUvC/HxOsQvE0MUV8NE1cfjvh9WeM5tiTFhylOLCXG9KadJzCLTbzCviOomUQ0vsTOl/ibuhXNARoNYpFG4C08K4HOt7w2Wtx8mHYRy9JHKZyowqqvMx+Hrw15AImHSGq0rpHTqmc883Z1FRkgVM50/djmwENHHI9Xld9cAx9Nbn14R/8FschcEfc3Uyy6YVNEIMJBNLv9pPn2q/LFc/jD4tVlHapTt7pfg2Rxse0n4vzZcZZ2n4r03hkldgRbP8r4QHk68bV9vUhPY7dfUUN3AdaIEYt0SupNKH2QUDPaavVOmUJCU4qi0TQ4RDiXp5H+5/6J5SHmZrCHWTb5zNV0TaPWN3bgIkH+oeA1fx/eQHgdwDgAJ1W9OvyMMerK4RQNC+/9BgE8Ro1XEWBA12gq0pcNgEIrPy6X+7HVckoZf2AHnK3DWtgWXqVrpPFb4cdk7Uehkl+qA3OaYehSd1dNFffBp5bwBpSRmZFnB8M4KUo8Z0oBzb3sYEXRR4wIM31h1S52Z3noUbwJ3dPPKswOREMh10Zv0U57NB1mphbta5dy8nNZzZhHe9ckHTmBTN58DFkmxfJ78kQdMDuh/yEkr8=
  app: agile-mountain-55679
