language: java
jdk: oraclejdk8
addons:
  mariadb: '10.0'
before_install:
- mysql -e 'CREATE DATABASE menti;'
notifications:
  slack:
    rooms:
      secure: 'P+wc53q+tot4DHoPDO7Vt6ZoJVovR1pJ2404d8/wK4KtDnKMnxSkaAaOR+j5gnAcCrY/fhZpiEgfQJhW46zzh3ce84H7CwgMhVNLS2WUluPT8nRmpUE7fZcgDflGCItUtVG/6QwExXESOvs2GiFhzGFs1P958zEk3vHRW8tB1r71KGTBmIjAWlm4GyhEL4X5+Dh/UZJEqe8f77PqVUKG6/aSOAnqKd8/tm3DENyTbIQkUA8346sd+C9W+wvrNEzzd7+jXq0VDVlFchZ0jhD73ncLutbEr1rsnAc1/1Db9lbvOuFohY6UUVvwh9gUXEgbMnP7mALXTvdUmc47KXxxOrLILzYirhlX4HxL6MgOSeTixNoIC6LMWO4OctOxQgi01hQcQdRO/aEwnQvlSBwFjT5XbBZbED7eZFF4J8sUQ9mBvh/VLfL8KfhwUCz7KOk1kkTL//4+OZTN/fbCylx90WQBa/OHSk7phBzfzETiRfxbXDrIlIsYANLVBk4dcJYvcYClWrYyHMitWS69FhOQOzkribCkt1U1j6qkJwzMrJ9rj24KfJgxKppoQNHk45njU785eBeVc1Bq62QUbLdlzK//kPrjUC3ycKlVSxEQ/MZFLZDDmksCSscjdq7fie46yRRRFQprQT8E+R8QEPX0ImnOSF8v+T3wikAkNRjmbAU='
    on_success: always
    on_failure: always
